### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by estahn** [garethr/kubetest#23]

**Comment by garethr** [comment]
Not dead, although I've not had a lot of time to actively work on it recently. I've been somewhat looking to find other people interesting in helping maintain it as well.

**Comment by estahn** [comment]
Gareth, I would be interested in helping to maintain this project as we
have started using it quite a bit.

It could possibly replace Helmtest as well. Probably just needs a helm
plugin.

What do you need to move this along?

**Comment by garethr** [comment]
Thanks @estahn. I'd say the best first step would be to fix or improve something in the current code. There are a few issues from users on GitHub or anything you think could be improved from your own usage. I'll review, get merged and if that works out I'll add you as a maintainer.

If that works out happy to move it to a standalone org on GitHub as well.

I've been wanting to write a helm plugin for a while and not gotten round to it too, great idea.
